'use client'

import { motion } from 'framer-motion';

// 您原来 page.js 里的所有显示逻辑现在都在这里
export default function TermsContent() {
  return (
    <div className="function-page pt-24 pb-16">
      <motion.main
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-4xl mx-auto px-4 prose lg:prose-xl"
      >
        <h1 className="text-5xl font-bold text-gradient mb-8">Terms of Service</h1>
        <p className="text-lg text-gray-500">Last updated: August 06, 2025</p>

        <div className="space-y-6 text-gray-700">
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing and using Labubu Maker ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.</p>
          
          <h2>2. Use of the Service</h2>
          <p>Labubu Maker provides AI-powered tools to create digital artwork. You agree to use the Service responsibly and not to upload any content that is illegal, harmful, or infringes on the rights of others.</p>

          <h2>3. User Content</h2>
          <p>You retain ownership of the original images you upload. By using the service, you grant us a non-exclusive, worldwide, royalty-free license to use, reproduce, and modify your uploaded content solely for the purpose of operating and providing the Service to you. You are responsible for the content you upload and must ensure you have the necessary rights.</p>
          
          <h2>4. Generated Content</h2>
          <p>The images generated by the AI are provided for your personal, non-commercial use. While you can share and display them, ownership of AI-generated art is a complex legal area. We do not make any claims of copyright over the final generated images.</p>

          <h2>5. Disclaimers</h2>
          <p>The Service is provided "as is" without any warranties of any kind. We do not guarantee that the Service will be uninterrupted or error-free. The AI-generated content may sometimes be unexpected or imperfect.</p>

          <h2>6. Limitation of Liability</h2>
          <p>In no event shall Labubu Maker be liable for any indirect, incidental, or consequential damages arising out of your use of the Service.</p>
          
          <h2>7. Contact Us</h2>
          <p>If you have any questions about these Terms, you can contact us at: hello@labubu-maker.com</p>
        </div>
      </motion.main>
    </div>
  );
}